### ISSUE TITLE
JS Errors for wordpress pages

### ISSUE THREAD

**Issue by oneezy** [trofrigo/polymer-theme#4]
Everything appears to be working as expected, but javascript errors are still showing up in the console,

![image](https://cloud.githubusercontent.com/assets/7369575/23817909/80029466-05bc-11e7-9b79-ba99fa724029.png)

**Comment by rodrigosancho** [comment]
Hi @oneezy ,

At a first time, it intended to be a feature instead of a bug. 

Since you can not select a Polymer's template for your pages in the Wordpress's backoffice and with the [Wordpress template hierarchy system](https://developer.wordpress.org/files/2014/10/template-hierarchy.png) in mind, I tried to mimic this behavior in the template's shell. For instance, if the page that your are about to load has a slug called `game`, the shell will load the first match into the next sequence:

1. template-game.html
2. template-page-detail.html
3. template-404.html

This system allows you to have specific templates for some pages. The problem is that every time that shell fails loading a template, it throws an error. There is not a quiet loading mode in the [Polymer's importHref](https://www.polymer-project.org/1.0/docs/api/Polymer.Base#method-importHref).

Due to this errors, I fear that this is another thing that I will have to move into the backend's config element. So I'm thinking about remove this functionality.

What are your thoughts about this?

**Comment by oneezy** [comment]
Ahh, i see what you mean.

That is a really nice feature to have..those js errors, even though there not doing any major harm are always annoying. 

If you were to move it into the wp backend, are you saying that it would be possible to keep this feature?

**Comment by rodrigosancho** [comment]
I think so. I'm already working on this, I wanna have something functional for this week

**Comment by oneezy** [comment]
awesome. I've started developing a custom theme w/ your wp `polymer-theme`. will keep an eye out for any bugs and let you know what i come across

**Comment by oneezy** [comment]
hey @trofrigo , does your new additions address this issue? I haven't tested yet

**Comment by rodrigosancho** [comment]
Hi! 

I've just push some features, I'm still testing it, it's almost a whole new application. 

Now in the backoffice of your wordpress's installation, you will find an admin's section. At the moment, only the templates are working, the other settings are mocked. 

If you are updating to this last version, remember to do a `bower install`
